// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKW7Eq5tIpAaErJxEpGnZ-1kPrnCbag0',
    appId: '1:738628071:android:10ada7e2715daf57866d42',
    messagingSenderId: '738628071',
    projectId: 'azu-s-cube-helper',
    databaseURL: 'https://azu-s-cube-helper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'azu-s-cube-helper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbVUiPoSWdKWi7rEcGVOd0Z6MV3a8mDms',
    appId: '1:738628071:ios:b433c8c031252e1e866d42',
    messagingSenderId: '738628071',
    projectId: 'azu-s-cube-helper',
    databaseURL: 'https://azu-s-cube-helper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'azu-s-cube-helper.appspot.com',
    iosClientId: '738628071-i3g1q1jt307i7d31qd48atp4s5kd4elt.apps.googleusercontent.com',
    iosBundleId: 'com.example.cubehelper',
  );
}
